language: node_js
node_js:
- 4.2.2
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_script:
- bower install
deploy:
  provider: heroku
  api_key:
    secure: JzYO4RIJHr7NPnJGtL09KKkchqhyREpSa7GqX3HsJPOKq09VeSASRomrAk1vK+u+ys9p8kfP6lZSw0UTRUolp9uTRx+npJUmwBXxujo0DvMAo2Z6TuOknQ7pumKlDJ5KGKCfQzAyrmdfWrPoU0EDp29lhp8ajtgSur6x1rTwsOx6QOXlB6Zc/eNYWnggdUEEwKKXrFtXJ8i661fsWGsyQBurlLnErtcBoc+dyzHHEYzN0D1xAwkmWkGhq1saCg815Ijn0fYXF4Bl0ocB8xHrDlTL/ziy3M4caaG60hdWlBGbREKvgMBwKMIgCNSGpll8nbVrb2RgUG9WQ8wDYn/txcovTI7ZT++/mYLh3qKGed2guNcQf3LP+kuihfOumm70sCaOSlGkXHflUvA35XrOWNqfvnWilfuwdrTg/w7Mkfw6ZfHW2fo8NStpAANGQiRAup5uKTWH1dO8qNtiuur0ysZrCUlBa7LNIModA4cPIcLIaITCmBahiz4XsIw/K1ZoIhajN/oP8AduSB/9wOjQjK9yfLTakcXFB4Sray7tgee6oizMuSQ0A81Y/Ea4F+Y7Kz3C/KzF88kG3vbPRprl9QU2ezz33o+gMli78Hqmru2j/xd4xzbHSNUOGTLKSpSxDccPDv+ufkUoq6UEqUYJJZqHJnbtQ8TdGUw2yjo0xl4=
  app: peli-maailma
  on:
    repo: TeemuKoivisto/peliMaailma
